### ISSUE TITLE
Error when running example on windows platform

### ISSUE THREAD

**Issue by parischap** [TylorS/typed-fp#14]
I tried to run the example on my PC and got the following errors:

```
C:\Users\JEROME\Documents\MesDeveloppements\websites\typed-fp>pnpm example

> typed-fp@1.0.0 example C:\Users\JEROME\Documents\MesDeveloppements\websites\typed-fp
> pnpm typed serve


> typed-fp@1.0.0 typed C:\Users\JEROME\Documents\MesDeveloppements\websites\typed-fp
> pnpm tsx ./packages/cli/src/cli.ts "serve"

(node:12376) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
[@typed/vite-plugin]: Setting up TypeScript Project...
[@typed/vite-plugin]: TypeScript Project setup complete.
Forced re-optimization of dependencies
@vavite/reloader: Loading server entry

  typed  

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
[@typed/vite-plugin]: Generated browser module for pages
[@typed/vite-plugin]: Generated browser module for other-pages
@vavite/reloader: Loading server entry
@vavite/reloader: Loading server entry (x2)
@most/types doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
@nrwl/nx-plugin doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
ts-toolbelt doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
@most/types doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
@nrwl/nx-plugin doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
ts-toolbelt doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
@most/types doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
@nrwl/nx-plugin doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
ts-toolbelt doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
[@typed/vite-plugin]: Generated api module for api
[@typed/vite-plugin]: Generated runtime module for other-pages
[@typed/vite-plugin]: Generated runtime module for pages
[@typed/vite-plugin]: Generated HTML module for index.html
[@typed/vite-plugin]: Generated HTML module for other.html
Failed to load url ./pageslayout.js (resolved id: ./pageslayout.js) in C:/Users/JEROME/Documents/MesDeveloppements/websites/typed-fp/example/pages.runtime.__generated__.ts. Does the file exist?
Failed to load url ./pages♀allback.js (resolved id: ./pages♀allback.js) in C:/Users/JEROME/Documents/MesDeveloppements/websites/typed-fp/example/pages.runtime.__generated__.ts. Does the file exist?
Failed to load url ./pageshome.js (resolved id: ./pageshome.js) in C:/Users/JEROME/Documents/MesDeveloppements/websites/typed-fp/example/pages.runtime.__generated__.ts. Does the file exist?
Failed to load url ./pagearenvironment.js (resolved id: ./pagearenvironment.js) in C:/Users/JEROME/Documents/MesDeveloppements/websites/typed-fp/example/pages.runtime.__generated__.ts. Does the file exist?
Failed to load url ./pageaar.js (resolved id: ./pageaar.js) in C:/Users/JEROME/Documents/MesDeveloppements/websites/typed-fp/example/pages.runtime.__generated__.ts. Does the file exist?
Failed to load url ./pageaaz.js (resolved id: ./pageaaz.js) in C:/Users/JEROME/Documents/MesDeveloppements/websites/typed-fp/example/pages.runtime.__generated__.ts. Does the file exist?
Failed to load url ./pages♀oo♀oo.js (resolved id: ./pages♀oo♀oo.js) in C:/Users/JEROME/Documents/MesDeveloppements/websites/typed-fp/example/pages.runtime.__generated__.ts. Does the file exist?
Failed to load url ./other-pageslayout.js (resolved id: ./other-pageslayout.js) in C:/Users/JEROME/Documents/MesDeveloppements/websites/typed-fp/example/other-pages.runtime.__generated__.ts. Does the file exist?
Failed to load url ./other-pages♀allback.js (resolved id: ./other-pages♀allback.js) in C:/Users/JEROME/Documents/MesDeveloppements/websites/typed-fp/example/other-pages.runtime.__generated__.ts. Does the file exist?
Failed to load url ./other-pageshome.js (resolved id: ./other-pageshome.js) in C:/Users/JEROME/Documents/MesDeveloppements/websites/typed-fp/example/other-pages.runtime.__generated__.ts. Does the file exist?
eactcounter.jsx) in C:/Users/JEROME/Documents/MesDeveloppements/websites/typed-fp/example/other-pages.runtime.__generated__.ts. Does the file exist?
Failed to load url ./other-pagessveltesvelte.js (resolved id: ./other-pagessveltesvelte.js) in C:/Users/JEROME/Documents/MesDeveloppements/websites/typed-fp/example/other-pages.runtime.__generated__.ts. Does the file exist?
@vavite/reloader: Loading server entry
@vavite/reloader: Loading server entry (x2)
@vavite/reloader: Loading server entry (x3)
[@typed/vite-plugin]: Generated browser module for pages
[@typed/vite-plugin]: Generated browser module for other-pages
@vavite/reloader: Loading server entry (x4)
Failed to resolve import "./pageslayout.js" from "C:\Users\JEROME\Documents\MesDeveloppements\websites\typed-fp\example\pages.browser.__generated__.ts". Does the file exist?
Failed to resolve import "./other-pageslayout.js" from "C:\Users\JEROME\Documents\MesDeveloppements\websites\typed-fp\example\other-pages.browser.__generated__.ts". Does the file exist?
@vavite/reloader: Loading server entry
10:09:33 [vite] Error when evaluating SSR module C:/Users/JEROME/Documents/MesDeveloppements/websites/typed-fp/example/other-pages.runtime.__generated__.ts: failed to import "./other-pageslayout.js"
|- Error: Failed to load url ./other-pageslayout.js (resolved id: ./other-pageslayout.js) in C:/Users/JEROME/Documents/MesDeveloppements/websites/typed-fp/example/other-pages.runtime.__generated__.ts. Does the file exist?
    at loadAndTransform (c:/Users/JEROME/Documents/MesDeveloppements/websites/typed-fp/node_modules/.pnpm/vite@4.3.1_@types+node@18.16.0/node_modules/vite/dist/node/chunks/dep-24daf00c.js:53335:21)

10:09:33 [vite] Error when evaluating SSR module C:/Users/JEROME/Documents/MesDeveloppements/websites/typed-fp/example/server.ts: failed to import "C:/Users/JEROME/Documents/MesDeveloppements/websites/typed-fp/example/other-pages.runtime.__generated__.ts"
|- Error: Failed to load url ./other-pageslayout.js (resolved id: ./other-pageslayout.js) in C:/Users/JEROME/Documents/MesDeveloppements/websites/typed-fp/example/other-pages.runtime.__generated__.ts. Does the file exist?
    at loadAndTransform (c:/Users/JEROME/Documents/MesDeveloppements/websites/typed-fp/node_modules/.pnpm/vite@4.3.1_@types+node@18.16.0/node_modules/vite/dist/node/chunks/dep-24daf00c.js:53335:21)

node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Failed to load url ./other-pageslayout.js (resolved id: ./other-pageslayout.js) in C:/Users/JEROME/Documents/MesDeveloppements/websites/typed-fp/example/other-pages.runtime.__generated__.ts. Does the file exist?
    at loadAndTransform (c:/Users/JEROME/Documents/MesDeveloppements/websites/typed-fp/node_modules/.pnpm/vite@4.3.1_@types+node@18.16.0/node_modules/vite/dist/node/chunks/dep-24daf00c.js:53335:21) {
  code: 'ERR_LOAD_URL'
}

Node.js v20.1.0
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by TylorS** [comment]
Hey @mjljm thank you for the bug report, I have a feeling this is faulty somewhere within @typed/compiler which is generating the files which utilize these imports. Potentially [here](https://github.com/TylorS/typed-fp/blob/development/packages/compiler/src/makeRuntimeModule.ts#L90), but also maybe there's something off with my usage of `ts-morph` which I use to scan source directories for the types they export [here](https://github.com/TylorS/typed-fp/blob/development/packages/compiler/src/type-helpers.ts#L9). 

I'll definitely have a look soon and see what I can figure out.

**Comment by TylorS** [comment]
Hey @mjljm, just wanted to ping here to let you know this isn't dead to me 😄 

I've been working on re-writing all of the rendering to support proper hydration, I'll be done with it in the next week or two. Afterwards, I'll be re-writing the compiler, which I'm pretty confident now is the source of these issues, to include much more robustness and some new features I've really wanted while building my first production application with these libraries.

**Comment by parischap** [comment]
Hi Tylor,  it s not dead to me either. We are all facing the same problems:
days are only 24h long...

**Comment by TylorS** [comment]
Hey @mjljm, it's a totally different example at the moment, but I _believe_ the current example should run on Windows as it just utilizes Vite and plugins directly with no compiler breaking things. Also includes a lot of updates I was alluding to.

I intend to rewrite the compiler soon, and I'll take care to ensure it works in a Windows environment

**Comment by TylorS** [comment]
Hey @mjljm, I'm gonna go ahead and close this for now. I haven't fully replaced the compiler just yet, and thus I believe all the vite stuff should work in all environments. I also don't have the same examples. 

I think we can open another issue if we encounter Windows issues again, as it won't be related to the same bugs that caused this initially.
